-- AUTOGENERATED BY gopkg.in/spacemonkeygo/dbx.v1
-- DO NOT EDIT
CREATE TABLE scriptures (
	pk bigserial NOT NULL,
	created_at timestamp with time zone NOT NULL,
	id text NOT NULL,
	chapter bigint NOT NULL,
	book text NOT NULL,
	verse_number bigint NOT NULL,
	verse_text text NOT NULL,
	hint text NOT NULL,
	PRIMARY KEY ( pk ),
	UNIQUE ( id )
);
