-- AUTOGENERATED BY gopkg.in/spacemonkeygo/dbx.v1
-- DO NOT EDIT
CREATE TABLE citations (
	pk INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL,
	mem_date TIMESTAMP NOT NULL,
	id TEXT NOT NULL,
	reference TEXT,
	author TEXT,
	text TEXT NOT NULL,
	book TEXT,
	hint TEXT,
	year INTEGER,
	PRIMARY KEY ( pk ),
	UNIQUE ( id )
);
