-- AUTOGENERATED BY gopkg.in/spacemonkeygo/dbx.v1
-- DO NOT EDIT
CREATE TABLE citations (
	pk bigserial NOT NULL,
	created_at timestamp with time zone NOT NULL,
	mem_date timestamp with time zone NOT NULL,
	id text NOT NULL,
	reference text,
	author text,
	text text,
	book text,
	hint text,
	year bigint,
	PRIMARY KEY ( pk ),
	UNIQUE ( id )
);
