-- AUTOGENERATED BY gopkg.in/spacemonkeygo/dbx.v1
-- DO NOT EDIT
CREATE TABLE scriptures (
	pk INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL,
	id TEXT NOT NULL,
	chapter INTEGER NOT NULL,
	book TEXT NOT NULL,
	verse_number INTEGER NOT NULL,
	verse_text TEXT NOT NULL,
	hint TEXT NOT NULL,
	PRIMARY KEY ( pk ),
	UNIQUE ( id )
);
